### ISSUE TITLE
Web UI shows session in January of the Year 1 (A.D.)

### ISSUE THREAD

**Issue by strobus** [itsnoproblem/pokt-calculator#51]
Today I am seeing a session for January of the year 1 (12/31/1, 7:03:58 PM). See attached screenshot.
<img width="1275" alt="Screen Shot 2022-05-27 at 11 54 18 AM" src="https://user-images.githubusercontent.com/22136798/170735826-4aa8b69a-672a-40f4-ad0c-46b23ee54613.png">

**Comment by itsnoproblem** [comment]
Hey @strobus thanks for the bug report!  I am so far unable to recreate this issue, but I can see from your screenshot that there is a problem.  If you are able, can you please DM me on discord to troubleshoot?

**Comment by strobus** [comment]
Thank you for the fix!
